// Lista de barrios de Posadas, Misiones
export const POSADAS_NEIGHBORHOODS = [
  "A-3-2",
  "Apóstoles",
  "Belén",
  "Bernardino Rivadavia",
  "Botánico",
  "Bº 1º de Mayo",
  "Bº 200 Viviendas",
  "Bº Agua y Energía",
  "Bº Camba Cuá",
  "Bº Itaembé Guazú",
  "Bº Itaembé Miní",
  "Bº Las Flores",
  "Bº Las Tacuaras",
  "Bº San Jorge",
  "Bº San Martín",
  "Bº Villa Blosset",
  "Bº Villa Cabello",
  "Bº Villa Urquiza",
  "Centro",
  "Cerro Corá",
  "Chacra 181",
  "Ciudad Nueva",
  "Colonia Mbopicuá",
  "Don Santiago",
  "El Bosque",
  "El Porvenir",
  "Fátima",
  "Ferroviario",
  "Flamingo",
  "Fracción VII",
  "Franja de Avance",
  "Gastón Dumón",
  "Itaembé Miní",
  "Jardín",
  "Las Marias",
  "Las Misiones",
  "Las Palmas",
  "Los Lapachos",
  "Lote 8",
  "Mitre",
  "Nemesio Parma",
  "Nuevo Horizonte",
  "Palomar",
  "Parque Urbano",
  "Pérez Companc",
  "Pocito",
  "Quebrachos",
  "Rincón",
  "San Cayetano",
  "San Isidro",
  "San Lorenzo",
  "San Miguel",
  "San Roque",
  "Santa Catalina",
  "Santa Rita",
  "Timbó",
  "Torres de Fátima",
  "Tres Bocas",
  "Tres de Mayo",
  "Tropical",
  "Valle del Paraná",
  "Villa Baja",
  "Villa Lanús",
  "Villa Sarita",
  "Yacyretá",
  "Yariguarenda",
  "Zaiman",
].sort()
